### ISSUE TITLE
Exception: Agent with unique id (30, 3) already added to scheduler

### ISSUE THREAD

**Issue by wildan32** [Pieter-Cawood/M-TA-Prioritized-MAPD#1]
I am very interested with your code to make sorting robot , but when I run your code with 
python3 main.py
it appear Exception: Agent with unique id (30, 3) already added to scheduler

can you give solution of your code ?
![Screenshot from 2022-02-14 12-09-16](https://user-images.githubusercontent.com/20807683/153803706-6a674921-7fef-4bcc-b5e9-49acc469c500.png)

**Comment by Pieter-Cawood** [comment]
Could you debug and show me the contents of the world.agents variable, the mesa package threw that exception? Apparently there's an agent with the same unique-id it needs to model.
https://github.com/Pieter-Cawood/M-TA-Prioritized-MAPD/blob/927d773f3ebd218e07cfa990f1283e0ddd1a3656/mesa_server.py#L58

**Comment by CPZCPZ** [comment]
same problem here. I did't make any changes in your code, just run `python main.py` , then got this error too. Could you please help to fix it? Thanks a lot.

**Comment by Pieter-Cawood** [comment]
Thank you for pointing this out. Mesa no longer allows multiple agents in one location. And since I treat parking locations as agents it caused an exception. I modified their BaseScheduler class and updated the repository so it works like it used to :)

Alternatively : install the recommend pip package version of Mesa.
